# Generated by Django 6.1.1 on 2026-09-23 03:56

import core.storage_backend
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backend.mediaStoarge, upload_to=student.models.media_storage_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.CharField(max_length=11),
        ),
    ]
